; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = ../src

[env:disco_f746ng]
platform = ststm32@~18.0.0
board = disco_f746ng
framework = zephyr
extra_scripts = pre:.scripts/sources_platform.py
                pre:.scripts/sources_xf_core.py
                pre:.scripts/sources_xf_port_zephyr.py

# Remove predefined compiler flags defined by PlatformIO's build system. Otherwise,
# it is not possible to overwrite the compiler flags in the 'build_flags' configuration
# parameter!
build_unflags = -std=c99 -std=c++11 -Os

build_flags = 
    -std=c11
    -std=c++14
    -O0
    -I.
    -I../src/
    -I../../common/
    -I../../../src/xf/include
    -I../../../src/xf/port
    -I../../../src/xf/port/zephyr
    -I../../../src/mdw
    -I../../../src/platform/f7-disco-zephyr
    -I../../../src/platform/f7-disco-zephyr/mcu
    -D XF_PORT_ZEPHYR=1
    -D USE_PLATFORM_F7_DISCO_ZEPHYR_TRACE=1
    -D USE_PLATFORM_F7_DISCO_ZEPHYR_SYSMEM=1
    -D TRACE_ENABLE_TIMESTAMP

; Note: Filter paths are relative to the cmake file location
build_src_filter = 
    +<*>
    +<../../src/*> ; Include test application code

debug_server = ${platformio.packages_dir}/tool-openocd/bin/openocd
    -s ${platformio.packages_dir}/tool-openocd/scripts
    -f interface\stlink.cfg
    -c "transport select hla_swd"
    -f target\stm32f7x.cfg
    -c "reset_config srst_only srst_nogate connect_assert_srst"
